apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test
  description: test
  annotations:
    github.com/project-slug: zorns-eu/springTest
    backstage.io/techdocs-ref: github:https://github.com/zorns-eu/springTest
spec:
  type: service
  lifecycle: experimental
  owner: guest
